"""expand_hr_contact_schema

Revision ID: 18fd6d0c75f4
Revises: a6bf302e9f4d
Create Date: 2026-02-10 01:43:14.763941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fd6d0c75f4'
down_revision: Union[str, None] = 'a6bf302e9f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_contacts', sa.Column('name', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('company', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('profile_url', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('job_link', sa.String(), nullable=True))
    op.add_column('hr_contacts', sa.Column('post_preview', sa.Text(), nullable=True))
    op.add_column('hr_contacts', sa.Column('matched_keywords', sa.JSON(), nullable=True))
    op.add_column('hr_contacts', sa.Column('extracted_at', sa.DateTime(), nullable=True))
    op.alter_column('hr_contacts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('hr_contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hr_contacts', 'job_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('fk_hr_contacts_user_id', 'hr_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'hr_contacts', 'users', ['user_id'], ['id'])
    op.drop_column('hr_contacts', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_contacts', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hr_contacts', type_='foreignkey')
    op.create_foreign_key('fk_hr_contacts_user_id', 'hr_contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hr_contacts', 'job_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hr_contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hr_contacts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('hr_contacts', 'extracted_at')
    op.drop_column('hr_contacts', 'matched_keywords')
    op.drop_column('hr_contacts', 'post_preview')
    op.drop_column('hr_contacts', 'job_link')
    op.drop_column('hr_contacts', 'post_url')
    op.drop_column('hr_contacts', 'profile_url')
    op.drop_column('hr_contacts', 'company')
    op.drop_column('hr_contacts', 'title')
    op.drop_column('hr_contacts', 'name')
    # ### end Alembic commands ###
